# Generated by Django 3.0.5 on 2020-06-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('province', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('confirm', models.IntegerField()),
                ('confirm_add', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('dead', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('confirm', models.IntegerField()),
                ('confirm_add', models.IntegerField()),
                ('suspect', models.IntegerField()),
                ('suspect_add', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('heal_add', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('dead_add', models.IntegerField()),
            ],
        ),
    ]
