# Generated by Django 3.0.5 on 2020-06-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='confirm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='confirm_add',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dead',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='heal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='province',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='confirm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='confirm_add',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='dead',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='dead_add',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='heal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='heal_add',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='suspect',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='suspect_add',
            field=models.IntegerField(null=True),
        ),
    ]
