# Generated by Django 3.0.5 on 2020-06-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200607_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='datetime',
            new_name='ds',
        ),
    ]
